name: Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Give Maven wrapper permission
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test

      - name: Build application
        run: ./mvnw clean package -DskipTests